Repository arduino/portenta-c33-fwuploader-plugin, pull requests merged in 2023-08, with the labels that each got.

#2 Add support for portenta-c33
  .gitignore
  .licenses/go/github.com/arduino/arduino-cli/executils.dep.yml
  .licenses/go/github.com/arduino/arduino-cli/i18n.dep.yml
  .licenses/go/github.com/arduino/fwuploader-plugin-helper.dep.yml
  .licenses/go/github.com/arduino/go-paths-helper.dep.yml
  .licenses/go/github.com/arduino/go-xmodem/ymodem.dep.yml
  .licenses/go/github.com/arduino/uno-r4-wifi-fwuploader-plugin/serial.dep.yml
  .licenses/go/github.com/creack/goselect.dep.yml
  .licenses/go/github.com/leonelquinteros/gotext.dep.yml
  .licenses/go/github.com/leonelquinteros/gotext/plurals.dep.yml
  .licenses/go/github.com/pkg/errors.dep.yml
  .licenses/go/github.com/spf13/cobra.dep.yml
  .licenses/go/github.com/spf13/pflag.dep.yml
  .licenses/go/go.bug.st/relaxed-semver.dep.yml
  .licenses/go/go.bug.st/serial.dep.yml
  .licenses/go/go.bug.st/serial/unixutils.dep.yml
  .licenses/go/golang.org/x/exp/constraints.dep.yml
  .licenses/go/golang.org/x/exp/slices.dep.yml
  .licenses/go/golang.org/x/exp/slog.dep.yml
  .licenses/go/golang.org/x/exp/slog/internal.dep.yml
  .licenses/go/golang.org/x/exp/slog/internal/buffer.dep.yml
  .licenses/go/golang.org/x/sys/unix.dep.yml
  .licenses/go/golang.org/x/text/internal/language.dep.yml
  .licenses/go/golang.org/x/text/internal/language/compact.dep.yml
  .licenses/go/golang.org/x/text/internal/tag.dep.yml
  .licenses/go/golang.org/x/text/language.dep.yml
  .licenses/go/gopkg.in/yaml.v3.dep.yml
  README.md
  Taskfile.yml
  go.mod
  go.sum
  main.go
  sketches/certificate/build/arduino.renesas_portenta.portenta_c33/certificate.ino.bin
  sketches/certificate/certificate.ino
  sketches/certificate/certificates.h
  sketches/certificate/sketch.yaml
  sketches/certificate/ymodem.cpp
  sketches/certificate/ymodem.h
  sketches/reboot/build/arduino.renesas_portenta.portenta_c33/reboot.ino.bin
  sketches/reboot/reboot.ino
  sketches/reboot/sketch.yaml
  sketches/version/build/arduino.renesas_portenta.portenta_c33/version.ino.bin
  sketches/version/sketch.yaml
  sketches/version/version.ino
Labels: topic: code, topic: infrastructure

#4 Change S3 bucket path
  .github/workflows/release-go-task.yml
  extras/package_index.json.template
Labels: type: imperfection, topic: code

#5 Distribute only for: win64, linux64 and Macos intel 64
  .github/workflows/release-go-task.yml
  DistTasks.yml
  extras/package_index.json.template
Labels: topic: code
